# =========================================================================
# Makefile - One-command build for the compiler.
# =========================================================================
#
# Targets:
#
#   make          - default target; runs `all` (clean -> build -> run).
#   make clean    - delete every generated artifact (objects, output files,
#                   the compiled exe). Lets you start fresh.
#   make build    - generate parser, generate lexer, compile to Compiler.exe
#                   (does not run it).
#   make run      - invoke ./Compiler.exe on src.txt to compile your source.
#
# Phony targets are listed below so `make` treats them as commands, not
# as files to be checked for existence on disk.
# =========================================================================

.PHONY: all clean build bison flex comp

# Default target: wipe outputs, rebuild, then run on src.txt.
all: clean build run

# Remove every generated file.
#   - Compiler.exe       : the built binary
#   - Parser.tab.c / .h  : bison output (parser + token header)
#   - lex.yy.c           : flex output (the scanner)
#   - Parser.output      : bison's optional verbose grammar log (-v flag)
#   - .vscode            : editor scratch dir, kept clean
#   - *.out              : the four runtime output files
clean:
	rm -rf Compiler.exe Parser.tab.c Parser.tab.h lex.yy.c Parser.output .vscode SymbolTable.out SymbolTableVisualiser.out SemanticAnalysis.out Quadruples.out

# Build the compiler by chaining: bison -> flex -> gcc.
build: bison flex comp

# Run the freshly-built compiler on src.txt.  yyparse reads from there,
# emits Quadruples.out / SymbolTable.out / etc. into the working dir.
run:
	./Compiler.exe src.txt

# ---- Bison: generate Parser.tab.c + Parser.tab.h from Parser.y ----------
#   -d  also emit a header file with the token enum (consumed by Lexer.l)
#   -v  also write Parser.output - a HUGE verbose log of states & conflicts
#       (useful when chasing shift/reduce conflicts)
bison:
	bison.exe -d -v Parser.y

# ---- Flex: generate lex.yy.c from Lexer.l ------------------------------
flex:
	flex.exe Lexer.l

# ---- GCC: compile EVERYTHING into one executable -----------------------
# Compilation units, in order:
#   SymbolTableDefs/Symbol.c            - Symbol struct lifecycle
#   SymbolTableDefs/SymbolList.c        - per-bucket linked list
#   SymbolTableDefs/ScopeSymbolTable.c  - one scope's hash table
#   SymbolTableDefs/SymbolTable.c       - the stacked symbol table
#   globals.c                            - shared mutable state (definitions)
#   utils.c                              - allocateTempVar + visualiser
#   Parser.tab.c                         - generated by bison
#   lex.yy.c                             - generated by flex
#
# Output: Compiler.exe (a Windows-style filename; on Linux you'd just
# get "Compiler", that's fine).
comp:
	gcc.exe SymbolTableDefs/Symbol.c SymbolTableDefs/SymbolList.c SymbolTableDefs/ScopeSymbolTable.c SymbolTableDefs/SymbolTable.c globals.c utils.c Parser.tab.c lex.yy.c -o Compiler.exe
